CREATE PROCEDURE FI_SP_VerificaBeneficiario
 @CPF VARCHAR(14),
    @ID BIGINT,
    @IDCLIENTE BIGINT
AS
BEGIN
    SELECT 1 FROM BENEFICIARIOS WHERE CPF = @CPF AND IDCLIENTE = @IDCLIENTE AND ID <> @ID
END
